package platformtruth

func disposition(id, name, system, action, reason, evidence, xiaoQ, risk string) DomainDisposition {
	return DomainDisposition{ID: id, Name: name, System: system, Disposition: action, Reason: reason, Evidence: evidence, XiaoQ: xiaoQ, OwnerScope: "single_owner", Risk: risk}
}

// domainDispositions classifies every current internal/domain package. A test
// compares this registry with the filesystem so an unclassified package cannot
// silently enter the platform.
func domainDispositions() []DomainDisposition {
	return []DomainDisposition{
		disposition("actionpolicy", "行动策略", "kernel", "reuse", "保留确定性风险与审批策略机制", "implemented", "not_applicable", "high"),
		disposition("aftersales", "售后", "fact", "adapt", "与订单、退款、争议观察期确定性接线", "implemented", "deferred", "high"),
		disposition("agentlearning", "Agent 学习", "frozen", "freeze", "更多自治学习不进入当前路线", "implemented", "not_applicable", "medium"),
		disposition("agentrule", "Agent 规则", "kernel", "adapt", "仅保留小Q与安全执行需要的规则", "implemented", "not_applicable", "high"),
		disposition("allocation", "成本分配", "fact", "adapt", "统一到可复算财务对象和来源", "implemented", "deferred", "high"),
		disposition("approval", "Owner 审批", "kernel", "reuse", "所有高风险写入的统一决策门", "implemented", "not_applicable", "high"),
		disposition("brand", "品牌", "fact", "reuse", "商品主数据组成部分", "implemented", "deferred", "medium"),
		disposition("candidate", "候选商品", "fact", "migrate", "迁移到市场机会与商品机会边界", "implemented", "deferred", "medium"),
		disposition("category", "类目", "fact", "reuse", "商品与渠道规则的确定性主数据", "implemented", "deferred", "medium"),
		disposition("competitor", "竞品", "fact", "adapt", "必须绑定来源、观察时间和市场 tuple", "implemented", "deferred", "low"),
		disposition("completeness", "商品完整度", "support", "adapt", "作为商品草稿校验器而非独立事实源", "implemented", "deferred", "medium"),
		disposition("compliance", "合规", "fact", "adapt", "区分规则引用、核验事实和未知", "implemented", "deferred", "high"),
		disposition("consolidation", "商品聚合", "support", "adapt", "仅处理身份合并并保留来源链", "implemented", "deferred", "medium"),
		disposition("content", "商品内容", "fact", "adapt", "绑定来源、版本、语言、权利和批准状态", "implemented", "deferred", "medium"),
		disposition("cost", "成本", "fact", "adapt", "统一估算、实际与已对账成本语义", "implemented", "deferred", "high"),
		disposition("dashboard", "经营看板", "support", "adapt", "只聚合可信事实并标明 mock/unknown", "implemented", "deferred", "low"),
		disposition("decision", "经营决策与反馈", "decision", "rebuild", "补齐问题、目标、动作、执行、观测、偏差和下一动作", "planned", "deferred", "high"),
		disposition("demandcase", "候选市场比较", "decision", "reuse", "承载市场 tuple、证据、反证与 Owner 裁决", "implemented", "active", "medium"),
		disposition("entropy", "Agent 熵", "frozen", "freeze", "不属于当前 Owner 经营纵向单元", "implemented", "not_applicable", "low"),
		disposition("evolution", "Agent 进化", "frozen", "freeze", "更多自治升级已冻结", "implemented", "not_applicable", "medium"),
		disposition("exceptions", "经营异常", "fact", "adapt", "异常必须引用真实对象和处理状态", "implemented", "deferred", "medium"),
		disposition("exchangerate", "汇率", "fact", "adapt", "保存币种对、来源、观察时间和用途", "implemented", "deferred", "high"),
		disposition("experiment", "经营事实核验案卷", "fact", "migrate", "保留追踪能力但移除实验与因果语义", "implemented", "active", "high"),
		disposition("finance", "经营财务", "fact", "adapt", "统一账项身份、来源、币种和对账", "implemented", "deferred", "high"),
		disposition("foreigntrade", "旧外贸模块", "frozen", "delete", "未进入当前路由且领域职责已被现行模块覆盖", "implemented", "not_applicable", "medium"),
		disposition("imagegen", "商品图片生成", "support", "adapt", "只生成草稿并绑定来源、权利、版本和审批", "implemented", "deferred", "medium"),
		disposition("importbatch", "批量导入", "support", "adapt", "导入必须保留来源、幂等和错误报告", "implemented", "deferred", "high"),
		disposition("integrations", "渠道连接器", "support", "adapt", "按已选市场启用并区分 mock/sandbox/production", "implemented", "deferred", "high"),
		disposition("inventory", "库存", "fact", "reuse", "保留确定性库存状态与审计边界", "implemented", "deferred", "high"),
		disposition("landedcost", "到岸成本", "fact", "adapt", "并入完整成本证据与可复算模型", "implemented", "deferred", "high"),
		disposition("listing", "Listing", "fact", "reuse", "保留草稿、渠道映射和外部状态", "implemented", "deferred", "high"),
		disposition("listingtask", "上架任务", "fact", "adapt", "保持草稿批准与真实发布独立", "implemented", "deferred", "high"),
		disposition("logistics", "物流方案", "fact", "adapt", "区分报价、规则和实际履约", "implemented", "deferred", "high"),
		disposition("loop", "旧闭环模块", "frozen", "migrate", "不得继续表达错误经营闭环，能力迁往决策系统", "implemented", "not_applicable", "high"),
		disposition("metabolism", "Agent 代谢", "frozen", "freeze", "自治治理不属于当前经营路径", "implemented", "not_applicable", "low"),
		disposition("mock", "模拟数据", "frozen", "delete", "生产经营入口不得展示或回退为模拟事实", "mock", "not_applicable", "medium"),
		disposition("notification", "通知", "support", "adapt", "通知只呈现真实事件并保留关联", "implemented", "deferred", "medium"),
		disposition("operationlog", "操作审计", "kernel", "reuse", "统一追加式审计与完整性验证", "implemented", "not_applicable", "high"),
		disposition("orchestration", "旧多 Agent 编排", "frozen", "freeze", "小Q是唯一 Owner Agent，更多编排不扩建", "implemented", "not_applicable", "high"),
		disposition("order", "订单", "fact", "reuse", "记录渠道交易事实而不证明需求或因果", "implemented", "active", "high"),
		disposition("orderimport", "订单导入", "support", "adapt", "绑定渠道来源、幂等和订单身份", "implemented", "deferred", "high"),
		disposition("owner", "Owner 工作台", "collaboration", "adapt", "改为可信经营入口并移除硬编码状态", "implemented", "not_applicable", "low"),
		disposition("personalrule", "Owner 个人规则", "decision", "adapt", "规则需版本化并绑定 Owner 决策", "implemented", "deferred", "medium"),
		disposition("platform", "销售渠道", "fact", "adapt", "只登记经市场选择的渠道与账号状态", "implemented", "deferred", "high"),
		disposition("platformfee", "平台费用", "fact", "adapt", "规则估算与实际扣费分开", "implemented", "deferred", "high"),
		disposition("platformtruth", "平台真相合同", "kernel", "reuse", "统一方向、事实等级和领域职责", "implemented", "not_applicable", "low"),
		disposition("price", "价格", "fact", "adapt", "区分建议、批准价格和渠道实际价格", "implemented", "deferred", "high"),
		disposition("productanalysis", "商品分析", "decision", "adapt", "输出推断与建议，不写成商品事实", "implemented", "deferred", "medium"),
		disposition("productimage", "商品图片任务", "support", "adapt", "仅生成和处理内部图片草稿，必须绑定来源、权利、版本、Owner与审批，不得自动发布", "implemented", "deferred", "high"),
		disposition("producthub", "商品档案聚合", "support", "adapt", "只读聚合规范商品事实并显示来源", "implemented", "deferred", "medium"),
		disposition("profit", "利润", "fact", "adapt", "估算利润与最终已对账利润分开", "implemented", "active", "high"),
		disposition("purchase", "采购", "fact", "adapt", "采购建议、批准、下单和收货状态分开", "implemented", "deferred", "high"),
		disposition("reliability", "可靠性评分", "support", "adapt", "评分是推断，必须显示输入和局限", "implemented", "deferred", "low"),
		disposition("report", "经营报告", "support", "adapt", "聚合事实时保留估算与对账等级", "implemented", "deferred", "low"),
		disposition("search", "统一搜索", "support", "reuse", "只读定位现有 Owner 数据", "implemented", "deferred", "low"),
		disposition("sentiment", "市场情绪", "decision", "adapt", "仅作为带来源的推断输入", "implemented", "deferred", "low"),
		disposition("settings", "系统设置", "kernel", "reuse", "Owner 配置入口受权限和审计保护", "implemented", "not_applicable", "high"),
		disposition("settlement", "结算", "fact", "adapt", "保持可信来源、同一对象和明细对账", "implemented", "active", "high"),
		disposition("shipping", "履约发运", "fact", "adapt", "绑定订单、包裹、承运商和外部状态", "implemented", "deferred", "high"),
		disposition("sku", "SKU", "fact", "reuse", "商品、供应商与渠道身份映射的核心对象", "implemented", "deferred", "medium"),
		disposition("sourcing", "AI 选品", "decision", "migrate", "迁往市场机会与商品机会决策，不直接宣称事实", "implemented", "deferred", "medium"),
		disposition("sourcing1688", "1688 私人收藏与受控草稿", "fact", "adapt", "按私人采集箱和经营闸门新顺序改造", "implemented", "active", "high"),
		disposition("supplier", "供应商", "fact", "adapt", "绑定主体身份、来源、报价和核验时间", "implemented", "deferred", "medium"),
		disposition("supplychain", "供应链编排", "support", "adapt", "协调采购、库存和履约但不复制状态", "implemented", "deferred", "high"),
		disposition("supplyevent", "供应链事件模型", "support", "reuse", "保留跨模块事实事件合同", "implemented", "not_applicable", "medium"),
		disposition("support", "客服", "fact", "adapt", "绑定订单、买家消息和售后处理事实", "implemented", "deferred", "high"),
		disposition("tariff", "关税", "fact", "adapt", "区分规则报价、估算税费和实际税费", "implemented", "deferred", "high"),
		disposition("trustscore", "Agent 信任分", "frozen", "freeze", "不以自治等级替代 Owner 审批", "implemented", "not_applicable", "medium"),
		disposition("workflow", "通用工作流", "support", "adapt", "只协调领域命令，不承载重复业务状态", "implemented", "deferred", "high"),
		disposition("xiaoq", "小Q", "collaboration", "adapt", "仅通过登记 Capability 调用领域服务", "implemented", "not_applicable", "high"),
	}
}
