package integrations

import (
	"context"
	"fmt"
	"math"
	"strconv"
	"strings"

	"github.com/lingmirror/backend-go/internal/platform/statemachine"
)

// Sandbox listing status constants. These mirror real platform statuses but
// are generated by the sandbox validation logic rather than an external API.
const (
	SandboxStatusCompleted                = "completed"
	SandboxStatusBlockedMissingData       = "blocked_missing_data"
	SandboxStatusBlockedLossMaking        = "blocked_loss_making"
	SandboxStatusFailedPlatformValidation = "failed_platform_validation"
)

// SandboxStatusTransitions defines allowed sandbox listing state transitions.
// pending -> simulating -> terminal (completed / blocked_*)
// blocked states can retry back to pending.
var SandboxStatusTransitions = map[string]map[string]bool{
	"pending":                              {"simulating": true},
	"simulating":                           {SandboxStatusCompleted: true, SandboxStatusBlockedMissingData: true, SandboxStatusBlockedLossMaking: true, SandboxStatusFailedPlatformValidation: true},
	SandboxStatusCompleted:                 {},
	SandboxStatusBlockedMissingData:        {"pending": true},
	SandboxStatusBlockedLossMaking:         {"pending": true},
	SandboxStatusFailedPlatformValidation:  {"pending": true},
}

// NewSandboxStateMachine creates a state machine for sandbox listing transitions.
func NewSandboxStateMachine() *statemachine.StateMachine {
	return statemachine.New(SandboxStatusTransitions)
}

// SandboxAdapter implements PlatformAdapter with simulated validation logic.
// It validates publish inputs against business rules (data completeness,
// profit heuristic, platform constraints) and returns mock results without
// making any real API calls.
type SandboxAdapter struct{}

// NewSandboxAdapter creates a SandboxAdapter. No dependencies needed —
// the sandbox does not make real API calls or access a database.
func NewSandboxAdapter() *SandboxAdapter {
	return &SandboxAdapter{}
}

// invalidSKUChars are characters that trigger failed_platform_validation.
var invalidSKUChars = []string{" ", "$", "#", "@", "!", "%", "^", "&", "*", "+", "=", "{", "}", "[", "]", "\\", "|", "<", ">", "?", "/", "~", "`", ":", ";", "\"", "'"}

// Publish validates a publish input against business rules and returns a
// simulated result. The five scenarios in priority order:
//
//  1. Missing required data   -> blocked_missing_data
//  2. Loss-making price       -> blocked_loss_making
//  3. Invalid platform values -> failed_platform_validation
//  4. All checks pass         -> completed (with mock IDs)
//  5. Dry-run mode            -> handled upstream by the service layer
func (a *SandboxAdapter) Publish(ctx context.Context, input *PublishInput) (*PublishResult, error) {
	// Scenario 1: Check required fields
	if input.ProductName == "" || input.Description == "" || len(input.SKUs) == 0 || len(input.Prices) == 0 {
		return a.blockedResult(SandboxStatusBlockedMissingData, "Missing required fields: product_name, description, at least one SKU with non-empty sku_code, and at least one price entry are required"), nil
	}

	firstSKU := input.SKUs[0]
	if firstSKU.SkuCode == "" {
		return a.blockedResult(SandboxStatusBlockedMissingData, "SKU code cannot be empty"), nil
	}
	if _, ok := input.Prices[firstSKU.SkuID]; !ok {
		return a.blockedResult(SandboxStatusBlockedMissingData, "Each SKU must have a price entry"), nil
	}

	// Scenario 2: Profit heuristic
	// cost = 50% of sale price, platform_fee = 15%, shipping = $5.00
	priceStr := input.Prices[firstSKU.SkuID]
	price, err := strconv.ParseFloat(priceStr, 64)
	if err != nil {
		return a.blockedResult(SandboxStatusBlockedMissingData, fmt.Sprintf("Invalid price value for SKU %d: %s", firstSKU.SkuID, priceStr)), nil
	}

	salePrice := price
	cost := salePrice * 0.5
	platformFee := salePrice * 0.15
	shipping := 5.00
	profit := salePrice - cost - platformFee - shipping

	if profit <= 0 {
		return a.blockedResult(SandboxStatusBlockedLossMaking, fmt.Sprintf("Listed price results in zero or negative profit: sale=%.2f cost=%.2f fee=%.2f shipping=%.2f profit=%.2f", salePrice, cost, platformFee, shipping, profit)), nil
	}

	// Scenario 3: Platform validation
	for _, ch := range invalidSKUChars {
		if strings.Contains(firstSKU.SkuCode, ch) {
			return a.blockedResult(SandboxStatusFailedPlatformValidation, fmt.Sprintf("SKU code contains invalid character: %s", ch)), nil
		}
	}
	if input.CategoryID == 0 {
		return a.blockedResult(SandboxStatusFailedPlatformValidation, "Category ID is required and must be non-zero"), nil
	}

	// Scenario 4: Success
	sku := firstSKU.SkuCode
	platformProductID := "sandbox-" + sku
	platformURL := "https://sandbox.local/products/" + sku

	result := &PublishResult{
		PlatformProductID: platformProductID,
		PlatformSKU:       sku,
		PlatformURL:       platformURL,
		SyncMessage:       SandboxStatusCompleted,
		PublishedData: map[string]interface{}{
			"status":      SandboxStatusCompleted,
			"explanation": "All validation checks passed",
			"profit_breakdown": map[string]float64{
				"sale_price":   math.Round(salePrice*100) / 100,
				"cost":         math.Round(cost*100) / 100,
				"platform_fee": math.Round(platformFee*100) / 100,
				"shipping":     shipping,
				"profit":       math.Round(profit*100) / 100,
			},
		},
	}
	return result, nil
}

// SyncStatus returns a mock synced status.
func (a *SandboxAdapter) SyncStatus(ctx context.Context, input *SyncStatusInput) (string, error) {
	return "synced", nil
}

// ValidateCredentials returns mock success.
func (a *SandboxAdapter) ValidateCredentials(ctx context.Context, accountID int64) (bool, error) {
	return true, nil
}

// SyncInventory returns mock success.
func (a *SandboxAdapter) SyncInventory(ctx context.Context, input *SyncInventoryInput) (bool, error) {
	return true, nil
}

// PushTracking returns mock success.
func (a *SandboxAdapter) PushTracking(ctx context.Context, input *PushTrackingInput) (bool, error) {
	return true, nil
}

// FetchOrders returns an empty order list.
func (a *SandboxAdapter) FetchOrders(ctx context.Context, input *FetchOrdersInput) ([]*PlatformOrder, error) {
	return []*PlatformOrder{}, nil
}

// FetchSettlements returns an empty settlement list.
func (a *SandboxAdapter) FetchSettlements(ctx context.Context, input *FetchSettlementsInput) ([]*PlatformSettlement, error) {
	return []*PlatformSettlement{}, nil
}

// FetchReturns returns an empty return list.
func (a *SandboxAdapter) FetchReturns(ctx context.Context, input *FetchReturnsInput) ([]*PlatformReturn, error) {
	return []*PlatformReturn{}, nil
}

// blockedResult builds a PublishResult with the given status and explanation.
func (a *SandboxAdapter) blockedResult(status, explanation string) *PublishResult {
	return &PublishResult{
		SyncMessage: status,
		PublishedData: map[string]interface{}{
			"status":      status,
			"explanation": explanation,
		},
	}
}
