"""add_store_and_ai_agent_deep_dive_tables

Revision ID: f22e62fe526b
Revises: 6475f8b1d588
Create Date: 2026-06-22 17:34:10.530886
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f22e62fe526b'
down_revision: Union[str, None] = '6475f8b1d588'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_arbitration_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('business_type', sa.String(length=50), nullable=False, comment='业务类型: sku/campaign/order'),
    sa.Column('business_id', sa.String(length=100), nullable=False, comment='业务ID'),
    sa.Column('conflict_keys', postgresql.ARRAY(sa.Text()), nullable=False, comment='冲突的decision_id列表'),
    sa.Column('stage', sa.String(length=20), nullable=False, comment='仲裁阶段: policy/arbiter/manual'),
    sa.Column('policy_id', sa.Integer(), nullable=True, comment='命中的policy ID'),
    sa.Column('verdict', sa.String(length=20), nullable=True, comment='仲裁结论'),
    sa.Column('arbiter_output', sa.JSON(), nullable=True, comment='G0的完整输出'),
    sa.Column('resolved_by', sa.String(length=100), nullable=False, comment='system/arbiter_G0/用户名'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_decision_cache',
    sa.Column('cache_key', sa.String(length=64), nullable=False, comment='缓存Key (SHA256)'),
    sa.Column('decision_json', sa.JSON(), nullable=False, comment='缓存决策内容'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='过期时间'),
    sa.PrimaryKeyConstraint('cache_key')
    )
    op.create_table('agent_schedule_failure',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.String(length=20), nullable=False, comment='Agent标识'),
    sa.Column('store_id', sa.Integer(), nullable=False, comment='店铺ID'),
    sa.Column('decision_point', sa.String(length=50), nullable=False, comment='决策点'),
    sa.Column('error_msg', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('failed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='失败时间'),
    sa.Column('retry_count', sa.Integer(), nullable=True, comment='重试次数'),
    sa.Column('last_retry_at', sa.DateTime(timezone=True), nullable=True, comment='上次重试时间'),
    sa.Column('resolved', sa.Boolean(), nullable=True, comment='是否已解决'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_conflict_policy',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('agent_id_a', sa.String(length=20), nullable=False, comment='冲突参与方A'),
    sa.Column('agent_id_b', sa.String(length=20), nullable=False, comment='冲突参与方B'),
    sa.Column('decision_point', sa.String(length=50), nullable=False, comment='适用的决策点'),
    sa.Column('condition', sa.JSON(), nullable=True, comment='触发条件（可选，如金额范围）'),
    sa.Column('winner', sa.String(length=20), nullable=False, comment='冲突时谁的决策优先'),
    sa.Column('reason', sa.Text(), nullable=False, comment='预置理由'),
    sa.Column('priority', sa.Integer(), nullable=True, comment='匹配优先级'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stores',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='店铺名称'),
    sa.Column('platform_id', sa.BigInteger(), nullable=True, comment='关联平台ID'),
    sa.Column('platform_account_id', sa.String(length=100), nullable=True, comment='外部平台店铺/账号ID'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='状态: 0-禁用, 1-启用'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('after_sales_order',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False, comment='订单ID'),
    sa.Column('item_id', sa.BigInteger(), nullable=True, comment='订单明细ID（全单退货时为空）'),
    sa.Column('sku_id', sa.BigInteger(), nullable=False, comment='SKU ID'),
    sa.Column('return_quantity', sa.Integer(), nullable=False, comment='退货数量'),
    sa.Column('reason', sa.String(length=100), nullable=False, comment='退货原因: defective/wrong_item/customer_return/other'),
    sa.Column('status', sa.String(length=30), nullable=True, comment='状态: requested/approved/received/refunded/rejected'),
    sa.Column('refund_amount', sa.Numeric(precision=12, scale=2), nullable=True, comment='退款金额'),
    sa.Column('inspection_result', sa.Text(), nullable=True, comment='验货结果'),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True, comment='驳回原因'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='创建人'),
    sa.Column('approved_by', sa.String(length=100), nullable=True, comment='审批人'),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True, comment='审批时间'),
    sa.Column('rejected_by', sa.String(length=100), nullable=True, comment='驳回人'),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True, comment='驳回时间'),
    sa.Column('received_by', sa.String(length=100), nullable=True, comment='收货人'),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True, comment='收货时间'),
    sa.Column('refunded_by', sa.String(length=100), nullable=True, comment='退款操作人'),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True, comment='退款时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['item_id'], ['sales_order_item.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['sales_order.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('agent_decision', sa.Column('store_id', sa.Integer(), nullable=True, comment='店铺ID（null=全店铺通用）'))
    op.add_column('agent_decision', sa.Column('llm_model_used', sa.String(length=50), nullable=True, comment='实际使用的模型'))
    op.add_column('agent_decision', sa.Column('llm_errors', sa.JSON(), nullable=True, comment='LLM错误列表 [{timestamp, error_type, model}]'))
    op.add_column('agent_decision', sa.Column('cached', sa.Boolean(), nullable=True, comment='是否命中缓存'))
    op.add_column('agent_decision', sa.Column('archived', sa.Boolean(), nullable=True, comment='是否已归档'))
    op.add_column('agent_decision', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True, comment='归档时间'))
    op.create_foreign_key(None, 'agent_decision', 'stores', ['store_id'], ['id'])
    op.add_column('agent_pending_action', sa.Column('store_id', sa.Integer(), nullable=True, comment='店铺ID（null=全店铺通用）'))
    op.create_foreign_key(None, 'agent_pending_action', 'stores', ['store_id'], ['id'])
    op.add_column('agentos_action_proposal', sa.Column('store_id', sa.Integer(), nullable=True, comment='店铺ID（null=全店铺通用）'))
    op.add_column('agentos_action_proposal', sa.Column('approval_deadline', sa.DateTime(timezone=True), nullable=True, comment='审批截止时间'))
    op.add_column('agentos_action_proposal', sa.Column('escalation_level', sa.Integer(), nullable=True, comment='当前升级层级 (0=初始)'))
    op.add_column('agentos_action_proposal', sa.Column('auto_decision', sa.String(length=20), nullable=True, comment='超时后动作: reject/auto_execute'))
    op.add_column('agentos_command_execution', sa.Column('compensation', sa.JSON(), nullable=True, comment='补偿操作定义'))
    op.add_column('agentos_command_execution', sa.Column('compensated_by', sa.BigInteger(), nullable=True, comment='补偿记录ID（自引用）'))
    op.create_foreign_key(None, 'agentos_command_execution', 'agentos_command_execution', ['compensated_by'], ['id'])
    op.add_column('personal_rule', sa.Column('store_id', sa.Integer(), nullable=True, comment='店铺ID（null=全店铺通用）'))
    op.add_column('personal_rule', sa.Column('last_manual_edit_at', sa.DateTime(timezone=True), nullable=True, comment='最后手动编辑时间'))
    op.create_foreign_key(None, 'personal_rule', 'stores', ['store_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'personal_rule', type_='foreignkey')
    op.drop_column('personal_rule', 'last_manual_edit_at')
    op.drop_column('personal_rule', 'store_id')
    op.drop_constraint(None, 'agentos_command_execution', type_='foreignkey')
    op.drop_column('agentos_command_execution', 'compensated_by')
    op.drop_column('agentos_command_execution', 'compensation')
    op.drop_column('agentos_action_proposal', 'auto_decision')
    op.drop_column('agentos_action_proposal', 'escalation_level')
    op.drop_column('agentos_action_proposal', 'approval_deadline')
    op.drop_column('agentos_action_proposal', 'store_id')
    op.drop_constraint(None, 'agent_pending_action', type_='foreignkey')
    op.drop_column('agent_pending_action', 'store_id')
    op.drop_constraint(None, 'agent_decision', type_='foreignkey')
    op.drop_column('agent_decision', 'archived_at')
    op.drop_column('agent_decision', 'archived')
    op.drop_column('agent_decision', 'cached')
    op.drop_column('agent_decision', 'llm_errors')
    op.drop_column('agent_decision', 'llm_model_used')
    op.drop_column('agent_decision', 'store_id')
    op.drop_table('after_sales_order')
    op.drop_table('stores')
    op.drop_table('agent_conflict_policy')
    op.drop_table('agent_schedule_failure')
    op.drop_table('agent_decision_cache')
    op.drop_table('agent_arbitration_log')
    # ### end Alembic commands ###
