"""add_sourcing_1688_product

Revision ID: 4ad5419fa71c
Revises: 20260622_01
Create Date: 2026-06-22 11:05:39.016843
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4ad5419fa71c"
down_revision: Union[str, None] = "20260622_01"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sourcing_1688_product",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "source_url",
            sa.String(length=1000),
            nullable=False,
            comment="1688 商品链接",
        ),
        sa.Column("title", sa.String(length=500), nullable=True, comment="采集标题"),
        sa.Column(
            "price",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="采集供货价",
        ),
        sa.Column("moq", sa.Integer(), nullable=True, comment="最小起订量"),
        sa.Column(
            "supplier_name", sa.String(length=200), nullable=True, comment="供应商名称"
        ),
        sa.Column(
            "shop_url", sa.String(length=1000), nullable=True, comment="1688 店铺链接"
        ),
        sa.Column(
            "shop_location", sa.String(length=200), nullable=True, comment="店铺地区"
        ),
        sa.Column("images", sa.JSON(), nullable=True, comment="图片列表"),
        sa.Column("attributes", sa.JSON(), nullable=True, comment="属性列表"),
        sa.Column("sku_variants", sa.JSON(), nullable=True, comment="SKU 变体"),
        sa.Column("description", sa.Text(), nullable=True, comment="描述"),
        sa.Column(
            "package_length_cm",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="包装长(cm)",
        ),
        sa.Column(
            "package_width_cm",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="包装宽(cm)",
        ),
        sa.Column(
            "package_height_cm",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="包装高(cm)",
        ),
        sa.Column(
            "package_weight_kg",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="包装重量(kg)",
        ),
        sa.Column("raw_data", sa.JSON(), nullable=True, comment="完整原始 payload"),
        sa.Column(
            "status",
            sa.String(length=50),
            nullable=True,
            comment="状态: collected/imported/rejected",
        ),
        sa.Column(
            "product_id", sa.BigInteger(), nullable=True, comment="导入后的商品 ID"
        ),
        sa.Column(
            "supplier_id", sa.BigInteger(), nullable=True, comment="导入后的供应商 ID"
        ),
        sa.Column(
            "collected_by", sa.String(length=100), nullable=True, comment="采集人"
        ),
        sa.Column(
            "imported_by", sa.String(length=100), nullable=True, comment="导入人"
        ),
        sa.Column(
            "imported_at", sa.DateTime(timezone=True), nullable=True, comment="导入时间"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="更新时间",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["supplier.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_url"),
    )
    op.alter_column(
        "agentos_operation_log",
        "item_id",
        existing_type=sa.VARCHAR(length=128),
        comment="WorkItem ID (e.g. exception:42)",
        existing_nullable=False,
    )
    op.alter_column(
        "agentos_operation_log",
        "action",
        existing_type=sa.VARCHAR(length=32),
        comment="approve / reject / status_update",
        existing_nullable=False,
    )
    op.alter_column(
        "agentos_operation_log",
        "source_type",
        existing_type=sa.VARCHAR(length=32),
        comment="agent_action / exception / notification / listing_task",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "agentos_operation_log",
        "source_type",
        existing_type=sa.VARCHAR(length=32),
        comment=None,
        existing_comment="agent_action / exception / notification / listing_task",
        existing_nullable=True,
    )
    op.alter_column(
        "agentos_operation_log",
        "action",
        existing_type=sa.VARCHAR(length=32),
        comment=None,
        existing_comment="approve / reject / status_update",
        existing_nullable=False,
    )
    op.alter_column(
        "agentos_operation_log",
        "item_id",
        existing_type=sa.VARCHAR(length=128),
        comment=None,
        existing_comment="WorkItem ID (e.g. exception:42)",
        existing_nullable=False,
    )
    op.drop_table("sourcing_1688_product")
    # ### end Alembic commands ###
