"""add exchange_rate table

Revision ID: 6475f8b1d588
Revises: 4ad5419fa71c
Create Date: 2026-06-22 17:03:53.160301
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6475f8b1d588'
down_revision: Union[str, None] = '4ad5419fa71c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exchange_rate', 'from_currency',
               existing_type=sa.VARCHAR(length=10),
               comment='源货币',
               existing_comment='源货币 (如 CNY)',
               existing_nullable=False)
    op.alter_column('exchange_rate', 'to_currency',
               existing_type=sa.VARCHAR(length=10),
               comment='目标货币',
               existing_comment='目标货币 (如 RUB)',
               existing_nullable=False)
    op.alter_column('exchange_rate', 'rate',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               type_=sa.Numeric(precision=14, scale=6),
               comment='汇率',
               existing_comment='汇率 (1源货币 = x目标货币)',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exchange_rate', 'rate',
               existing_type=sa.Numeric(precision=14, scale=6),
               type_=sa.NUMERIC(precision=12, scale=6),
               comment='汇率 (1源货币 = x目标货币)',
               existing_comment='汇率',
               existing_nullable=False)
    op.alter_column('exchange_rate', 'to_currency',
               existing_type=sa.VARCHAR(length=10),
               comment='目标货币 (如 RUB)',
               existing_comment='目标货币',
               existing_nullable=False)
    op.alter_column('exchange_rate', 'from_currency',
               existing_type=sa.VARCHAR(length=10),
               comment='源货币 (如 CNY)',
               existing_comment='源货币',
               existing_nullable=False)
    # ### end Alembic commands ###
