"""add_notification_tables

Revision ID: 97ed4e419f78
Revises: 9c37d57f6a02
Create Date: 2026-06-17 17:32:27.013807
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97ed4e419f78'
down_revision: Union[str, None] = '9c37d57f6a02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rule',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='规则名称'),
    sa.Column('alert_type', sa.String(length=50), nullable=False, comment='预警类型'),
    sa.Column('enabled', sa.SmallInteger(), nullable=True, comment='是否启用: 0-禁用, 1-启用'),
    sa.Column('config', sa.JSON(), nullable=True, comment='配置 (如阈值、检查间隔等)'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='说明'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_type')
    )
    op.create_table('notification',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='接收用户ID'),
    sa.Column('alert_type', sa.String(length=50), nullable=False, comment='类型: inventory_low_stock/inventory_out_of_stock/settlement_pending/settlement_discrepancy/listing_failed/order_pending/system'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='标题'),
    sa.Column('content', sa.Text(), nullable=True, comment='内容'),
    sa.Column('link_url', sa.String(length=500), nullable=True, comment='跳转链接'),
    sa.Column('severity', sa.String(length=20), nullable=True, comment='严重程度: info/warning/error/critical'),
    sa.Column('is_read', sa.SmallInteger(), nullable=True, comment='是否已读: 0-未读, 1-已读'),
    sa.Column('source_id', sa.String(length=100), nullable=True, comment='来源ID (如 sku=123)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.alter_column('agent_pending_action', 'user_id',
               existing_type=sa.BIGINT(),
               comment='用户ID',
               existing_nullable=False)
    op.alter_column('agent_pending_action', 'agent_id',
               existing_type=sa.VARCHAR(length=20),
               comment='Agent标识',
               existing_nullable=False)
    op.alter_column('agent_pending_action', 'decision_id',
               existing_type=sa.BIGINT(),
               comment='关联决策ID',
               existing_nullable=True)
    op.alter_column('agent_pending_action', 'action_type',
               existing_type=sa.VARCHAR(length=50),
               comment='操作类型: replenish/price_adjust/discount_review/ad_action/notify',
               existing_nullable=False)
    op.alter_column('agent_pending_action', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='状态: pending/confirmed/executed/rejected',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('agent_pending_action', 'summary',
               existing_type=sa.VARCHAR(length=500),
               comment='操作摘要',
               existing_nullable=False)
    op.alter_column('agent_pending_action', 'action_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment='执行参数',
               existing_nullable=True)
    op.alter_column('agent_pending_action', 'execution_result',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment='执行结果',
               existing_nullable=True)
    op.alter_column('agent_pending_action', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_pending_action', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('inventory', 'locked_quantity',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='锁定库存',
               existing_server_default=sa.text('0'))
    op.alter_column('product', 'product_length_cm',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='商品长(cm)',
               existing_nullable=True)
    op.alter_column('product', 'product_width_cm',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='商品宽(cm)',
               existing_nullable=True)
    op.alter_column('product', 'product_height_cm',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='商品高(cm)',
               existing_nullable=True)
    op.alter_column('product', 'product_weight_kg',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='商品重量(kg)',
               existing_nullable=True)
    op.alter_column('product', 'package_length_cm',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='包装长(cm)',
               existing_nullable=True)
    op.alter_column('product', 'package_width_cm',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='包装宽(cm)',
               existing_nullable=True)
    op.alter_column('product', 'package_height_cm',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='包装高(cm)',
               existing_nullable=True)
    op.alter_column('product', 'package_weight_kg',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='包装重量(kg)',
               existing_nullable=True)
    op.alter_column('product', 'cargo_type',
               existing_type=sa.VARCHAR(length=50),
               comment='货品类型',
               existing_nullable=True,
               existing_server_default=sa.text("'normal'::character varying"))
    op.drop_column('sales_order', 'tracking_number')
    op.alter_column('sku', 'stock',
               existing_type=sa.INTEGER(),
               comment='库存（已弃用，请使用 Inventory.quantity）',
               existing_comment='库存',
               existing_nullable=True)
    op.alter_column('sku', 'weight',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='重量(kg，历史字段，不表示包装重量)',
               existing_comment='重量(kg)',
               existing_nullable=True)
    op.alter_column('sku', 'sku_length_cm',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='SKU包装长(cm)',
               existing_nullable=True)
    op.alter_column('sku', 'sku_width_cm',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='SKU包装宽(cm)',
               existing_nullable=True)
    op.alter_column('sku', 'sku_height_cm',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='SKU包装高(cm)',
               existing_nullable=True)
    op.alter_column('sku', 'sku_weight_kg',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='SKU包装重量(kg)',
               existing_nullable=True)
    op.drop_column('sku', 'package_weight_kg')
    op.drop_column('sku', 'package_length_cm')
    op.drop_column('sku', 'package_width_cm')
    op.drop_column('sku', 'package_height_cm')
    op.alter_column('system_config', 'config_key',
               existing_type=sa.VARCHAR(length=100),
               comment='配置键名',
               existing_nullable=False)
    op.alter_column('system_config', 'config_value',
               existing_type=sa.TEXT(),
               comment='配置值（明文，仅用于非敏感配置）',
               existing_nullable=True)
    op.alter_column('system_config', 'config_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment='配置值（JSON 格式）',
               existing_nullable=True)
    op.alter_column('system_config', 'is_secret',
               existing_type=sa.SMALLINT(),
               comment='是否敏感配置（前端脱敏显示）',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('system_config', 'description',
               existing_type=sa.VARCHAR(length=500),
               comment='配置说明',
               existing_nullable=True)
    op.alter_column('system_config', 'updated_by',
               existing_type=sa.BIGINT(),
               comment='更新人',
               existing_nullable=True)
    op.alter_column('system_config', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('system_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('system_config', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('system_config', 'updated_by',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='更新人',
               existing_nullable=True)
    op.alter_column('system_config', 'description',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='配置说明',
               existing_nullable=True)
    op.alter_column('system_config', 'is_secret',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment='是否敏感配置（前端脱敏显示）',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('system_config', 'config_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='配置值（JSON 格式）',
               existing_nullable=True)
    op.alter_column('system_config', 'config_value',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='配置值（明文，仅用于非敏感配置）',
               existing_nullable=True)
    op.alter_column('system_config', 'config_key',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='配置键名',
               existing_nullable=False)
    op.add_column('sku', sa.Column('package_height_cm', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('sku', sa.Column('package_width_cm', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('sku', sa.Column('package_length_cm', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('sku', sa.Column('package_weight_kg', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.alter_column('sku', 'sku_weight_kg',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='SKU包装重量(kg)',
               existing_nullable=True)
    op.alter_column('sku', 'sku_height_cm',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='SKU包装高(cm)',
               existing_nullable=True)
    op.alter_column('sku', 'sku_width_cm',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='SKU包装宽(cm)',
               existing_nullable=True)
    op.alter_column('sku', 'sku_length_cm',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='SKU包装长(cm)',
               existing_nullable=True)
    op.alter_column('sku', 'weight',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='重量(kg)',
               existing_comment='重量(kg，历史字段，不表示包装重量)',
               existing_nullable=True)
    op.alter_column('sku', 'stock',
               existing_type=sa.INTEGER(),
               comment='库存',
               existing_comment='库存（已弃用，请使用 Inventory.quantity）',
               existing_nullable=True)
    op.add_column('sales_order', sa.Column('tracking_number', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='运单号/追踪号'))
    op.alter_column('product', 'cargo_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='货品类型',
               existing_nullable=True,
               existing_server_default=sa.text("'normal'::character varying"))
    op.alter_column('product', 'package_weight_kg',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='包装重量(kg)',
               existing_nullable=True)
    op.alter_column('product', 'package_height_cm',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='包装高(cm)',
               existing_nullable=True)
    op.alter_column('product', 'package_width_cm',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='包装宽(cm)',
               existing_nullable=True)
    op.alter_column('product', 'package_length_cm',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='包装长(cm)',
               existing_nullable=True)
    op.alter_column('product', 'product_weight_kg',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='商品重量(kg)',
               existing_nullable=True)
    op.alter_column('product', 'product_height_cm',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='商品高(cm)',
               existing_nullable=True)
    op.alter_column('product', 'product_width_cm',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='商品宽(cm)',
               existing_nullable=True)
    op.alter_column('product', 'product_length_cm',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='商品长(cm)',
               existing_nullable=True)
    op.alter_column('inventory', 'locked_quantity',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='锁定库存',
               existing_server_default=sa.text('0'))
    op.alter_column('agent_pending_action', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_pending_action', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_pending_action', 'execution_result',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='执行结果',
               existing_nullable=True)
    op.alter_column('agent_pending_action', 'action_payload',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='执行参数',
               existing_nullable=True)
    op.alter_column('agent_pending_action', 'summary',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='操作摘要',
               existing_nullable=False)
    op.alter_column('agent_pending_action', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='状态: pending/confirmed/executed/rejected',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('agent_pending_action', 'action_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='操作类型: replenish/price_adjust/discount_review/ad_action/notify',
               existing_nullable=False)
    op.alter_column('agent_pending_action', 'decision_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='关联决策ID',
               existing_nullable=True)
    op.alter_column('agent_pending_action', 'agent_id',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Agent标识',
               existing_nullable=False)
    op.alter_column('agent_pending_action', 'user_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_table('alert_rule')
    # ### end Alembic commands ###
