"""add_exception_item_table

Revision ID: a44be0e405da
Revises: 97ed4e419f78
Create Date: 2026-06-17 17:46:56.502614
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a44be0e405da"
down_revision: Union[str, None] = "97ed4e419f78"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exception_item",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "source_module",
            sa.String(length=50),
            nullable=False,
            comment="来源模块: listing/shipping/settlement/finance",
        ),
        sa.Column(
            "source_type", sa.String(length=50), nullable=True, comment="来源类型"
        ),
        sa.Column("source_id", sa.BigInteger(), nullable=True, comment="来源ID"),
        sa.Column(
            "severity",
            sa.String(length=20),
            nullable=True,
            comment="严重程度: low/medium/high/critical",
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=True,
            comment="状态: open/assigned/resolved/ignored",
        ),
        sa.Column("title", sa.String(length=300), nullable=False, comment="异常标题"),
        sa.Column("description", sa.Text(), nullable=True, comment="异常描述"),
        sa.Column(
            "recommended_action",
            sa.String(length=500),
            nullable=True,
            comment="建议操作",
        ),
        sa.Column(
            "assigned_to", sa.String(length=100), nullable=True, comment="分配给"
        ),
        sa.Column(
            "resolved_at", sa.DateTime(timezone=True), nullable=True, comment="解决时间"
        ),
        sa.Column(
            "resolved_by", sa.String(length=100), nullable=True, comment="解决人"
        ),
        sa.Column("note", sa.Text(), nullable=True, comment="备注"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="更新时间",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("exception_item")
    # ### end Alembic commands ###
