"""Add agent_evolution_config and agent_nudge tables

Revision ID: f7f1f102ba7b
Revises: 20260618_02
Create Date: 2026-06-18 15:32:36.363344
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7f1f102ba7b'
down_revision: Union[str, None] = '20260618_02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_evolution_config',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('agent_id', sa.String(length=20), nullable=False, comment='Agent标识'),
    sa.Column('decision_point', sa.String(length=50), nullable=False, comment='决策点'),
    sa.Column('current_stage', sa.String(length=20), nullable=False, comment='当前自治阶段'),
    sa.Column('stage_updated_at', sa.DateTime(timezone=True), nullable=True, comment='阶段最后变更时间'),
    sa.Column('stage_updated_by', sa.String(length=20), nullable=True, comment='变更来源: manual/nudge/regret/system'),
    sa.Column('trust_score', sa.Numeric(precision=6, scale=2), nullable=True, comment='信任评分 0-100'),
    sa.Column('decision_count', sa.Integer(), nullable=True, comment='累计决策样本数'),
    sa.Column('adoption_rate', sa.Numeric(precision=5, scale=4), nullable=True, comment='采纳率'),
    sa.Column('avg_confidence', sa.Numeric(precision=5, scale=4), nullable=True, comment='平均置信度'),
    sa.Column('consistency_score', sa.Numeric(precision=5, scale=4), nullable=True, comment='规则覆盖一致性'),
    sa.Column('stability_score', sa.Numeric(precision=5, scale=4), nullable=True, comment='SPC 稳定性'),
    sa.Column('last_calculated_at', sa.DateTime(timezone=True), nullable=True, comment='信任评分最后计算时间'),
    sa.Column('nudge_last_shown_at', sa.DateTime(timezone=True), nullable=True, comment='上次 Nudge 提示时间'),
    sa.Column('nudge_dismissed_count', sa.Integer(), nullable=True, comment='Nudge 忽略次数'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'agent_id', 'decision_point', name='uq_agent_evolution')
    )
    op.create_table('agent_nudge',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('agent_id', sa.String(length=20), nullable=False, comment='Agent标识'),
    sa.Column('decision_point', sa.String(length=50), nullable=False, comment='决策点'),
    sa.Column('target_stage', sa.String(length=20), nullable=False, comment='目标晋升阶段'),
    sa.Column('trust_score_at_time', sa.Numeric(precision=6, scale=2), nullable=False, comment='提示时的信任评分'),
    sa.Column('score_components', sa.JSON(), nullable=True, comment='评分分量明细'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: pending/accepted/dismissed/expired'),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True, comment='响应时间'),
    sa.Column('cooling_until', sa.DateTime(timezone=True), nullable=True, comment='冷却截止时间（忽略后7天）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_nudge')
    op.drop_table('agent_evolution_config')
    # ### end Alembic commands ###
