'use client';
import Link from 'next/link';
import { Alert, Button, Card, Empty, Form, Input, Select, Space, Tag, Typography, message } from 'antd';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import apiClient from '@/lib/api-client';
import PageContainer from '@/components/ui/PageContainer';
type CaseItem={id:number;question:string;target:string;object_type:string;object_id:number;truth_status:string;unknowns:string[];manifest_sha256:string;created_at:string;latest_owner_decision?:{decision:string;created_at:string}};
type FactOption={object_type:string;object_id:number;label:string;truth_status:string;observed_at:string};
export default function BusinessDecisionPage(){const qc=useQueryClient();const[form]=Form.useForm();const objectType=Form.useWatch('object_type',form)??'platform_order_ingest';const cases=useQuery({queryKey:['business-decisions'],queryFn:async()=>(await apiClient.get<CaseItem[]>('/v1/business-decisions')).data??[]});const options=useQuery({queryKey:['business-decision-fact-options',objectType],queryFn:async()=>(await apiClient.get<FactOption[]>('/v1/business-decisions/fact-options',{object_type:objectType})).data??[]});const create=useMutation({mutationFn:async(v:{question:string;target:string;object_type:string;object_id:number;unknowns_text?:string})=>(await apiClient.post<CaseItem>('/v1/business-decisions',{...v,unknowns_text:undefined,unknowns:(v.unknowns_text??'').split('\n').map(x=>x.trim()).filter(Boolean),idempotency_key:`owner-case-${crypto.randomUUID()}`})).data!,onSuccess:()=>{message.success('决策案卷已冻结事实创建');form.resetFields();qc.invalidateQueries({queryKey:['business-decisions']})}});
 return <PageContainer title="经营决策与反馈"><Space direction="vertical" size={16} style={{width:'100%'}}><Alert type="info" showIcon message="先选权威事实，再由 Owner 决定" description="案卷创建只冻结已有经营事实，不会自动批准或执行行动。AI 建议、Owner 决定和受控执行保持分离。"/><Card title="创建经营决策案卷"><Form form={form} layout="vertical" initialValues={{object_type:'platform_order_ingest'}} onFinish={v=>create.mutate(v)}><Form.Item name="object_type" label="权威事实类型" rules={[{required:true}]}><Select options={[{value:'platform_order_ingest',label:'平台订单事实'},{value:'purchase_authority',label:'采购授权事实'}]}/></Form.Item><Form.Item name="object_id" label="选择 Owner 权威事实" rules={[{required:true}]}><Select loading={options.isLoading} showSearch optionFilterProp="label" options={(options.data??[]).map(x=>({value:x.object_id,label:`${x.label} · ${x.truth_status}`}))} notFoundContent="当前 Owner 暂无可用权威事实"/></Form.Item><Form.Item name="question" label="经营问题" rules={[{required:true,whitespace:true}]}><Input.TextArea rows={2}/></Form.Item><Form.Item name="target" label="判断目标" rules={[{required:true,whitespace:true}]}><Input/></Form.Item><Form.Item name="unknowns_text" label="仍然未知（每行一项）"><Input.TextArea rows={3}/></Form.Item>{create.error&&<Alert className="mb-4" type="error" showIcon message="案卷未创建" description={create.error.message}/>}<Button type="primary" htmlType="submit" loading={create.isPending}>冻结事实并创建案卷</Button></Form></Card><Card title="我的经营决策案卷">{cases.isLoading?'正在读取…':cases.error?<Alert type="error" showIcon message="案卷列表读取失败" description={cases.error.message}/>:cases.data?.length?<Space direction="vertical" style={{width:'100%'}}>{cases.data.map(x=><Card key={x.id} size="small" extra={<Link href={`/business-decisions/${x.id}`}>打开完整链</Link>}><Space wrap><Typography.Text strong>#{x.id} {x.question}</Typography.Text><Tag>{x.truth_status}</Tag>{x.latest_owner_decision&&<Tag color="blue">{x.latest_owner_decision.decision}</Tag>}</Space><Typography.Paragraph type="secondary">目标：{x.target} · 冻结 {x.object_type} #{x.object_id}</Typography.Paragraph></Card>)}</Space>:<Empty description="尚无经营决策案卷"/>}</Card></Space></PageContainer>}
