'use client';
import { useState } from 'react';
import { Alert, Button, Card, Descriptions, Empty, Input, message, Modal, Space, Table, Tag, Typography } from 'antd';
import { ArrowLeftOutlined } from '@ant-design/icons';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useParams, useRouter } from 'next/navigation';
import apiClient, { ApiError } from '@/lib/api-client'; import PageContainer from '@/components/ui/PageContainer';
import type { DemandDetail, MarketDecisionValue, MarketOwnerDecision, OwnerDecisionCard } from '@/types/demand-case';
const { Text }=Typography;
export default function DemandCaseDetailPage(){const {id=''}=useParams<{id:string}>();const router=useRouter();const qc=useQueryClient();const [decision,setDecision]=useState<MarketDecisionValue|null>(null);const [reason,setReason]=useState('');
 const detail=useQuery({queryKey:['demand-case',id],queryFn:async()=>(await apiClient.get<DemandDetail>(`/v1/demand-cases/${id}`)).data,enabled:!!id});
 const card=useQuery({queryKey:['demand-card',id],queryFn:async()=>(await apiClient.get<OwnerDecisionCard>(`/v1/demand-cases/${id}/decision-card`)).data,enabled:!!id});
 const ownerDecision=useQuery({queryKey:['demand-owner-decision',id],queryFn:async()=>{try{return (await apiClient.get<MarketOwnerDecision>(`/v1/demand-cases/${id}/owner-decision`)).data??null}catch(e){if(e instanceof ApiError&&e.status===404)return null;throw e}},enabled:!!id});
 const decide=useMutation({mutationFn:(input:{decision:MarketDecisionValue;reason:string})=>apiClient.post<MarketOwnerDecision>(`/v1/demand-cases/${id}/owner-decisions`,{...input,idempotency_key:`market-${id}-${crypto.randomUUID()}`}),onSuccess:()=>{message.success('Owner 市场决定已保存');setDecision(null);setReason('');void qc.invalidateQueries({queryKey:['demand-owner-decision',id]})},onError:(e:Error)=>message.error(e.message)}); const d=detail.data,c=card.data;
 return <PageContainer title={d?`${d.case.region} × ${d.case.consumer}`:'候选市场案件'} subtitle={d?.case.need_scenario} loading={detail.isLoading||card.isLoading} error={detail.isError||card.isError} errorMsg={(detail.error as Error|undefined)?.message||(card.error as Error|undefined)?.message} onRetry={()=>{void detail.refetch();void card.refetch()}} extra={<Button icon={<ArrowLeftOutlined/>} onClick={()=>router.push('/demand-cases')}>全部候选</Button>}>
  {c&&<Card title="Owner 六行决策卡" style={{marginBottom:16}}><Descriptions column={1} bordered items={[
   {key:'h',label:'我们怀疑什么',children:c.hypothesis},{key:'p',label:'已经证明什么',children:c.proven},{key:'n',label:'还不能证明什么',children:c.not_proven},{key:'x',label:'最强反证',children:c.strongest_counterevidence},{key:'a',label:'下一权限或成本',children:c.next_authority_or_cost},{key:'s',label:'停止线',children:c.stop_condition||'尚未冻结'}]}/></Card>}
  <Card title="Owner 市场决定" style={{marginBottom:16}}>{ownerDecision.data?<Space orientation="vertical" style={{width:'100%'}}><Descriptions column={1} bordered items={[{key:'d',label:'当前决定',children:<Tag>{ownerDecision.data.decision}</Tag>},{key:'r',label:'理由',children:ownerDecision.data.reason},{key:'t',label:'决定时间',children:ownerDecision.data.created_at}]}/>{ownerDecision.data.decision==='selected'&&<Button type="primary" onClick={()=>router.push(`/product-opportunities?demand_case_id=${id}&market_decision_id=${ownerDecision.data?.id}`)}>基于该市场创建商品机会</Button>}</Space>:<Space wrap><Button type="primary" disabled={d?.verdict?.status!=='experiment_ready'} onClick={()=>setDecision('selected')}>选择该市场</Button><Button danger onClick={()=>setDecision('rejected')}>淘汰该市场</Button><Text type="secondary">选择只授权创建商品机会，不会采购、发布或投放。</Text></Space>}</Card>
  {d?.verdict?.blockers?.length?<Alert type="warning" showIcon title="当前未知与阻塞" description={<Space wrap>{d.verdict.blockers.map(x=><Tag key={x}>{x}</Tag>)}</Space>} style={{marginBottom:16}}/>:<Alert type="info" showIcon title={d?.verdict?.status==='experiment_ready'?'研究材料已达到 Owner 审议门槛':'尚未评估或没有可证明的无阻塞结果'} style={{marginBottom:16}}/>}
  <Card title="证据与反证" style={{marginBottom:16}}><Table rowKey="id" pagination={false} dataSource={d?.evidence??[]} locale={{emptyText:<Empty description="尚无证据"/>}} columns={[{title:'作用',dataIndex:'kind',render:(v:string)=><Tag color={v==='counter'?'red':v==='conflict'?'orange':'blue'}>{v}</Tag>},{title:'维度',dataIndex:'dimension'},{title:'事实',dataIndex:'title'},{title:'真实性',dataIndex:'truth_status'},{title:'来源',render:(_,r)=><Space orientation="vertical" size={0}>{r.source_uri?<a href={r.source_uri} target="_blank" rel="noreferrer">查看原始来源</a>:<Text type="secondary">无可追溯来源</Text>}<Text type="secondary">{r.observed_at||'未记录观察时间'}</Text></Space>},{title:'Run',dataIndex:'run_id',render:(v:string)=><Text code>{v}</Text>} ]}/></Card>
  <Card title="不可变原始快照">{d?.snapshots?.length?<Descriptions column={1} items={d.snapshots.map(s=>({key:s.id,label:s.run_type,children:<Space><Text code>{s.run_id}</Text><a href={s.source_uri} target="_blank" rel="noreferrer">来源</a><Text type="secondary">SHA256 {s.raw_sha256.slice(0,12)}…</Text></Space>}))}/>:<Empty description="尚无研究快照"/>}</Card>
  <Modal title={decision==='selected'?'选择该市场':'淘汰该市场'} open={!!decision} okText="保存 Owner 决定" okButtonProps={{disabled:!reason.trim(),loading:decide.isPending}} onCancel={()=>{setDecision(null);setReason('')}} onOk={()=>decision&&decide.mutate({decision,reason})}><Alert type="warning" showIcon title="这是一条不可变 Owner 决定" description="选择只允许下一步创建商品机会；不会自动采购、发布或投放。" style={{marginBottom:12}}/><Input.TextArea aria-label="Owner 决定理由" value={reason} onChange={e=>setReason(e.target.value)} placeholder="说明选择或淘汰的业务理由" rows={4}/></Modal>
 </PageContainer>}
