CREATE TABLE IF NOT EXISTS order_profit_record (
    id BIGSERIAL PRIMARY KEY,
    order_id BIGINT NOT NULL,
    revenue DOUBLE PRECISION NOT NULL DEFAULT 0,
    cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    shipping_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    platform_fee DOUBLE PRECISION NOT NULL DEFAULT 0,
    payment_fee DOUBLE PRECISION NOT NULL DEFAULT 0,
    tariff_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    total_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    profit DOUBLE PRECISION NOT NULL DEFAULT 0,
    margin DOUBLE PRECISION NOT NULL DEFAULT 0,
    calculated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_order_profit_order_id ON order_profit_record(order_id);
