ALTER TABLE agent_trust_score
    ADD COLUMN IF NOT EXISTS feedback_adopted INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS feedback_rejected INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS listing_feedback_rate NUMERIC(5,4) NOT NULL DEFAULT 0;
