'use client';
import { useState } from 'react';
import { Alert, Button, Card, Descriptions, Empty, Form, Input, InputNumber, Radio, Select, Space, Spin, Tag, Typography, message } from 'antd';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useParams } from 'next/navigation';
import apiClient from '@/lib/api-client';
import PageContainer from '@/components/ui/PageContainer';
import { TruthStatusTag } from '@/features/xiaoq/components';
import type { XiaoQTruthStatus } from '@/features/xiaoq/types';
const {Paragraph,Text}=Typography;
interface DecisionCase{id:number;question:string;target:string;object_type:string;object_id:number;truth_status:XiaoQTruthStatus;unknowns:string[];manifest_sha256:string;created_at:string}
interface OwnerDecision{id:number;decision:string;reason:string;capability_id?:string;command_type?:string;target_type?:string;target_id?:string;input_sha256?:string;input_payload?:Record<string,unknown>;created_at:string}
interface Detail{case:DecisionCase;fact_snapshot:{source_table:string;source_observed_at:string;payload_sha256:string;truth_status:XiaoQTruthStatus};ai_recommendations:Array<{id:number;recommendation:string;rationale:string;truth_status:XiaoQTruthStatus;unknowns:string[]}>;owner_decisions:OwnerDecision[]}
interface Action{id:number;owner_decision_id:number;approval_id:number;capability_id:string;command_type:string;target_type:string;target_id:string;input_payload:Record<string,unknown>;input_sha256:string;status:string;command_business_id?:string;failure_message?:string}
interface ActionDetail{action:Action;observations:Array<{id:number;evidence_kind:string;truth_status:string;source_manifest_sha256:string;target_metric:string;actual_value:string}>;next_recommendations:Array<{id:number;recommendation_text:string;rationale:string;truth_status:string}>}
export function stableJSONStringify(value:unknown):string{if(Array.isArray(value))return`[${value.map(stableJSONStringify).join(',')}]`;if(value&&typeof value==='object')return`{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${JSON.stringify(k)}:${stableJSONStringify(v)}`).join(',')}}`;return JSON.stringify(value)}
async function sha(value:string){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return Array.from(new Uint8Array(d),b=>b.toString(16).padStart(2,'0')).join('')}
const labels:Record<string,string>={selected:'已选择受控行动',rejected:'拒绝',paused:'暂停',request_more_evidence:'要求补证'};
export default function BusinessDecisionDetailPage(){const id=Number(useParams()?.id);const qc=useQueryClient();const[form]=Form.useForm();const[show,setShow]=useState(false);const[actionID,setActionID]=useState<number>();const kind=Form.useWatch('decision',form);
 const detail=useQuery({queryKey:['business-decision',id],queryFn:async()=>(await apiClient.get<Detail>(`/v1/business-decisions/${id}`)).data!,enabled:id>0,retry:false});
 const actions=useQuery({queryKey:['business-feedback-actions',id],queryFn:async()=>{const all=(await apiClient.get<Action[]>('/v1/business-feedback/actions')).data??[];const ids=new Set((detail.data?.owner_decisions??[]).map(x=>x.id));return all.filter(x=>ids.has(x.owner_decision_id))},enabled:!!detail.data});
 const actionDetail=useQuery({queryKey:['business-feedback-action',actionID],queryFn:async()=>(await apiClient.get<ActionDetail>(`/v1/business-feedback/actions/${actionID}`)).data!,enabled:!!actionID});
 const decide=useMutation({mutationFn:async(v:Record<string,unknown>)=>{const approvalId=Number(v.approval_id);const key=`owner-business-decision-${id}-${crypto.randomUUID()}`;let input_payload:Record<string,unknown>|undefined,input_sha256='';if(v.decision==='selected'){try{input_payload=JSON.parse(String(v.input_payload_json))}catch{throw new Error('行动输入必须是有效 JSON')};input_sha256=await sha(stableJSONStringify(input_payload))}return apiClient.postApproved(`/v1/business-decisions/${id}/owner-decisions`,{...v,approval_id:undefined,input_payload_json:undefined,input_payload,input_sha256,manifest_sha256:detail.data?.case.manifest_sha256,idempotency_key:key},{approvalId,idempotencyKey:key})},onSuccess:()=>{message.success('Owner决定已不可变保存');setShow(false);form.resetFields();qc.invalidateQueries({queryKey:['business-decision',id]})}});
 const createAction=useMutation({mutationFn:async(v:{owner_decision_id:number;approval_id:number;idempotency_key:string})=>{const d=detail.data?.owner_decisions.find(x=>x.id===v.owner_decision_id);if(!d?.input_payload)throw new Error('该决定没有可恢复的exact input payload');return apiClient.post('/v1/business-feedback/actions',{...v,capability_id:d.capability_id,command_type:d.command_type,target_type:d.target_type,target_id:d.target_id,input_payload:d.input_payload})},onSuccess:()=>{message.success('行动已创建，尚未执行');actions.refetch()}});
 const execute=useMutation({mutationFn:(a:Action)=>apiClient.postApproved(`/v1/business-feedback/actions/${a.id}/execute`,{},{approvalId:a.approval_id,idempotencyKey:`execute-business-action-${a.id}`}),onSuccess:()=>{message.success('执行结果已保存');actions.refetch();if(actionID)actionDetail.refetch()}});
 const observe=useMutation({mutationFn:(v:Record<string,unknown>)=>apiClient.post(`/v1/business-feedback/actions/${actionID}/observations`,v),onSuccess:()=>{message.success('权威观测已保存');actionDetail.refetch()}});
 const recommend=useMutation({mutationFn:(v:Record<string,unknown>)=>apiClient.post(`/v1/business-feedback/actions/${actionID}/next-recommendations`,v),onSuccess:()=>{message.success('下一动作建议保存为 inferred');actionDetail.refetch()}});
 if(detail.isLoading)return<PageContainer title="经营决策案卷"><Card><Spin/></Card></PageContainer>;if(detail.error||!detail.data)return<PageContainer title="经营决策案卷"><Alert type="error" showIcon message="案卷加载失败"/></PageContainer>;const data=detail.data;
 return <PageContainer title={`经营决策案卷 #${data.case.id}`}><Space direction="vertical" size={16} style={{width:'100%'}}><Alert type="info" showIcon message="事实、AI建议、Owner决定、执行与反馈严格分层" description="刷新页面会从Owner隔离API恢复整条记录；任何步骤都不能替代exact审批或把inferred建议升级为事实。"/><Card title="经营问题" extra={<TruthStatusTag status={data.case.truth_status}/>}><Descriptions column={1} size="small" items={[{key:'q',label:'问题',children:data.case.question},{key:'t',label:'目标',children:data.case.target},{key:'o',label:'冻结对象',children:<Text code>{data.case.object_type} #{data.case.object_id}</Text>},{key:'s',label:'事实来源',children:`${data.fact_snapshot.source_table} · ${data.fact_snapshot.source_observed_at}`},{key:'h',label:'Manifest',children:<Text copyable code>{data.case.manifest_sha256}</Text>}]}/>{data.case.unknowns.length>0&&<Alert type="warning" showIcon message="仍然未知" description={data.case.unknowns.join('；')}/>}</Card>
 <Card title="AI 建议（不是决定）">{data.ai_recommendations.length?<Space direction="vertical" style={{width:'100%'}}>{data.ai_recommendations.map(r=><Card size="small" key={r.id}><TruthStatusTag status={r.truth_status}/><Paragraph>{r.recommendation}</Paragraph><Text type="secondary">{r.rationale}</Text></Card>)}</Space>:<Empty description="尚无AI建议"/>}</Card>
 <Card title="Owner决定" extra={<Button type="primary" onClick={()=>setShow(!show)}>记录决定</Button>}>{show&&<Form form={form} layout="vertical" initialValues={{decision:'request_more_evidence'}} onFinish={v=>decide.mutate(v)}><Form.Item name="decision" label="决定" rules={[{required:true}]}><Radio.Group options={[{label:'选择exact行动',value:'selected'},{label:'要求补证',value:'request_more_evidence'},{label:'暂停',value:'paused'},{label:'拒绝',value:'rejected'}]}/></Form.Item>{kind==='selected'&&<><Alert className="mb-3" type="warning" showIcon message="下列五项将不可变冻结"/><Form.Item name="capability_id" label="Capability ID" rules={[{required:true}]}><Input placeholder="command.price_update.v1"/></Form.Item><Form.Item name="command_type" label="Command type" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="target_type" label="目标类型" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="target_id" label="目标ID" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="input_payload_json" label="exact输入JSON" rules={[{required:true}]}><Input.TextArea rows={4}/></Form.Item></>}<Form.Item name="reason" label="你的理由" rules={[{required:true}]}><Input.TextArea rows={3}/></Form.Item><Form.Item name="approval_id" label="已批准的一次性审批 ID" rules={[{required:true}]}><InputNumber min={1}/></Form.Item><Button type="primary" htmlType="submit" loading={decide.isPending}>不可变保存 Owner 决定</Button></Form>}{data.owner_decisions.length?<Space direction="vertical" style={{width:'100%',marginTop:12}}>{data.owner_decisions.map(d=><Card size="small" key={d.id}><Space wrap><Tag color="blue">#{d.id} {labels[d.decision]??d.decision}</Tag>{d.capability_id&&<Text code>{d.capability_id} → {d.target_type} #{d.target_id}</Text>}</Space><Paragraph>{d.reason}</Paragraph></Card>)}</Space>:<Empty description="尚无 Owner 决定"/>}</Card>
 <Card title="受控执行与反馈（刷新可恢复）"><Alert type="info" showIcon message="selected决定不等于执行" description="创建与执行都会再次核验最新Owner决定、exact payload和审批。"/><Form layout="inline" style={{marginTop:12}} onFinish={v=>createAction.mutate(v)}><Form.Item name="owner_decision_id" label="selected决定" rules={[{required:true}]}><Select style={{width:220}} options={data.owner_decisions.filter(d=>d.decision==='selected').map(d=>({value:d.id,label:`#${d.id} ${d.command_type}`}))}/></Form.Item><Form.Item name="approval_id" label="审批ID" rules={[{required:true}]}><InputNumber min={1}/></Form.Item><Form.Item name="idempotency_key" label="幂等键" rules={[{required:true}]}><Input/></Form.Item><Button type="primary" htmlType="submit">创建待执行行动</Button></Form>{createAction.error&&<Alert className="mt-3" type="error" message={createAction.error.message}/>}<Space direction="vertical" style={{width:'100%',marginTop:12}}>{(actions.data??[]).map(a=><Card size="small" key={a.id} extra={<Space><Button onClick={()=>setActionID(a.id)}>查看反馈</Button><Button type="primary" disabled={a.status!=='approved_pending_execution'&&a.status!=='executing'} onClick={()=>execute.mutate(a)}>{a.status==='executing'?'恢复为待对账':'显式执行'}</Button></Space>}><Space wrap><Text strong>行动 #{a.id}</Text><Tag>{a.status}</Tag><Text code>{a.capability_id}</Text></Space>{a.failure_message&&<Alert type="error" message={a.failure_message}/>}</Card>)}</Space>
 {actionID&&actionDetail.data&&<Card size="small" className="mt-4" title={`行动 #${actionID} 反馈`}><Form layout="vertical" onFinish={v=>observe.mutate(v)}><Space wrap align="start"><Form.Item name="evidence_kind" label="证据作用" rules={[{required:true}]}><Select style={{width:130}} options={['support','counter','conflict'].map(x=>({value:x,label:x}))}/></Form.Item><Form.Item name="source_object_type" label="权威来源" rules={[{required:true}]}><Select style={{width:230}} options={['platform_order_ingest','order_final_profit_version','cash_reconciliation'].map(x=>({value:x,label:x}))}/></Form.Item><Form.Item name="source_object_id" label="来源ID" rules={[{required:true}]}><InputNumber min={1}/></Form.Item><Form.Item name="target_metric" label="目标指标" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="target_value" label="目标值"><Input/></Form.Item><Form.Item name="actual_value" label="实际值"><Input/></Form.Item></Space><Form.Item name="comparison_note" label="偏差说明"><Input.TextArea/></Form.Item><Button htmlType="submit" disabled={actionDetail.data.action.status!=='succeeded'}>保存权威观测</Button></Form>{actionDetail.data.observations.map(o=><Alert className="mt-2" key={o.id} message={`${o.evidence_kind} · ${o.target_metric}: ${o.actual_value}`} description={`${o.truth_status} · ${o.source_manifest_sha256}`}/>)}<Form layout="inline" style={{marginTop:12}} onFinish={v=>recommend.mutate(v)}><Form.Item name="recommendation_text" label="下一动作" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="rationale" label="理由" rules={[{required:true}]}><Input/></Form.Item><Button htmlType="submit" disabled={!actionDetail.data.observations.length}>保存inferred建议</Button></Form>{actionDetail.data.next_recommendations.map(r=><Alert className="mt-2" type="warning" key={r.id} message={r.recommendation_text} description={`${r.truth_status} · ${r.rationale}`}/>)}</Card>}</Card></Space></PageContainer>}
